### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by eed3si9n** [dwijnand/sbt1fports#2]
It might be helpful to write a readme on the workflow.
It said we have 10 more PRs to go, but I don't think that's true.
Am I supposed to edit https://github.com/dwijnand/sbt1fports/blob/master/src/main/scala/sbt1fports/data.scala?

**Comment by dwijnand** [comment]
Yeah, it's not a smooth experience in the slightest.

It might be possible that there are only 10 PRs that aren't accounted for in `prToFpMap` in data.scala. So those 10 + the ones marked "todo", or pending, etc are still todo.

IIRC since the existence of https://github.com/sbt/sbt/tree/topic/generate_doc the machinery that identifies which PR a commit belongs to broke (commit belongs to multiple branches).

I'll work on this tomorrow, and detail how it "works", as bad as it is.

**Comment by eed3si9n** [comment]
Here's my "workflow" (https://github.com/sbt/sbt/issues/2352):

```
$ git log --oneline | egrep -h "\(#|pull" | head -40 | sed -e 's/^/- [ ] /'
```
